spring:
  application:
    name: customer-service
  datasource:
    platform: postgres
    url: jdbc:postgresql://172.18.0.2:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update